/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/*

package org.vending.machine;

import org.fusesource.jansi.AnsiConsole;
import org.jline.builtins.SystemRegistry;
import org.jline.builtins.Widgets.TailTipWidgets;
import org.jline.builtins.Widgets.TailTipWidgets.TipType;
import org.jline.reader.EndOfFileException;
import org.jline.reader.LineReader;
import org.jline.reader.MaskingCallback;
import org.jline.reader.UserInterruptException;

public class App {

  private final LineReader reader;
  private final SystemRegistry systemRegistry;

  public App(LineReader reader, SystemRegistry systemRegistry) {
    this.reader = reader;
    this.systemRegistry = systemRegistry;
  }

  public static void main(String[] args) {

  }

  private void run() {

    AnsiConsole.systemInstall();
    try {
      new TailTipWidgets(reader, systemRegistry::commandDescription, 5, TipType.COMPLETER);

      var prompt = "vending-machine> ";
      String rightPrompt = null;

      // start the shell and process input until the user quits with Ctrl-D
      String line;
      while (true) {
        try {
          systemRegistry.cleanUp();
          line = reader.readLine(prompt, rightPrompt, (MaskingCallback) null, null);
          systemRegistry.execute(line);
        } catch (UserInterruptException e) {
          // Ignore
        } catch (EndOfFileException e) {
          return;
        } catch (Exception e) {
          systemRegistry.trace(e);
        }
      }
    } catch (Throwable t) {
      t.printStackTrace();
    } finally {
      AnsiConsole.systemUninstall();
    }

  }

}
*/

package org.vending.machine;

import org.jline.utils.AttributedString;
import org.jline.utils.AttributedStyle;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.shell.jline.PromptProvider;


@SpringBootApplication
public class App {

  public static void main(String[] args) throws Exception {
    ConfigurableApplicationContext context = SpringApplication.run(App.class, args);
  }

  @Bean
  public PromptProvider myPromptProvider() {
    return () -> new AttributedString("vending-machine:>",
        AttributedStyle.DEFAULT.foreground(AttributedStyle.YELLOW));
  }
}